steps:
  # build the container images
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID",
        "--build-arg",
        "GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET",
        "--build-arg",
        "NEXT_PUBLIC_URL=$_NEXT_PUBLIC_URL",
        "--build-arg",
        "NEXTAUTH_PUBLIC_URL=$_NEXTAUTH_PUBLIC_URL",
        "--build-arg",
        "NEXTAUTH_SECRET=$_NEXTAUTH_SECRET",
        "--build-arg",
        "NEXTAUTH_URL=$_NEXTAUTH_URL",
        "--build-arg",
        "NODE_ENV=$_NODE_ENV",
        "--build-arg",
        "SERVICE_ACCOUNT_KEY=$_SERVICE_ACCOUNT_KEY",
        "--build-arg",
        "NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL",
        "--build-arg",
        "OPENAI_API_KEY=$_OPENAI_API_KEY",
        "--build-arg",
        "FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID",
        "--build-arg",
        "FIREBASE_CLIENT_EMAIL=$_FIREBASE_CLIENT_EMAIL",
        "--build-arg",
        "FIREBASE_PRIVATE_KEY=$_FIREBASE_PRIVATE_KEY",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID",
        "--build-arg",
        "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID",
        "--build-arg",
        "GOOGLE_TEXT_TO_SPEECH_API_KEY=$_GOOGLE_TEXT_TO_SPEECH_API_KEY",
        "--build-arg",
        "ACCESS_KEY=$_ACCESS_KEY",
        "--build-arg",
        "DISCORD_WEBHOOK_URL=$_DISCORD_WEBHOOK_URL",
        "-t",
        "gcr.io/$PROJECT_ID/reading-advantage-web",
        "./web",
      ]

  # push the container images to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/reading-advantage-web"]

  # Deploy container images to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "reading-advantage-web",
        "--image",
        "gcr.io/$PROJECT_ID/reading-advantage-web",
        "--timeout=60m",
        "--region",
        "asia-southeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - gcr.io/$PROJECT_ID/reading-advantage-web

options:
  logging: CLOUD_LOGGING_ONLY
