steps:
- name: node:18.14.2
  entrypoint: npm
  args: ["install"]
- name: node:18.14.2
  entrypoint: npm
  args: ["run", "build-env"]
  env:
    - 'SERVICE_ACCOUNT_KEY=${_SERVICE_ACCOUNT_KEY}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"